let name = "Nathan";
let age = 18;
let pnumber = 09662254504;
let email = "20197905@s.unaguio.edu";
let maddress = "Alumit";
let pr = "BSCS";
let idnum = 20197905;
let yrlvl = "First year"
let sctn = "IAA2";
document.getElementById("nm").innerHTML = name;
document.getElementById("ag").innerHTML = age;
document.getElementById("num").innerHTML = pnumber;
document.getElementById("em").innerHTML = email;
document.getElementById("madd").innerHTML = maddress;
document.getElementById("prog").innerHTML = pr;
document.getElementById("id").innerHTML = idnum;
document.getElementById("lvl").innerHTML = yrlvl;
document.getElementById("sec").innerHTML = sctn;